run:
  timeout: 5m

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/go-viper/encoding)
  golint:
    min-confidence: 0
  goimports:
    local-prefixes: github.com/go-viper/encoding

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - exportloopref
    - gci
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
